# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'TriangleTots' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Turbo Native for iOS
  pod 'Turbo', '~> 7.1'

  target 'TriangleTots' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TriangleTots' do
    # Pods for testing
  end
end
